import { ArrowLeft, ArrowRight, ArrowUpRight } from 'lucide-react'
import Link from 'next/link'
import { notFound } from 'next/navigation'
import { projectBySlug, projects } from '@/data/projects'
import { SiteHeader } from '@/components/SiteHeader'

export function generateStaticParams() { return projects.map(({ slug }) => ({ slug })) }

export default async function ProjectPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const project = projectBySlug(slug)
  if (!project) notFound()
  const index = projects.findIndex(({ slug: itemSlug }) => itemSlug === slug)
  const next = projects[(index + 1) % projects.length]
  return <><SiteHeader /><main className={`case-study case-study--${project.accent}`}><Link className="back-link" href="/#work"><ArrowLeft size={17} /> Back to work</Link><div className="case-study__layout"><aside className="case-study__rail"><p className="eyebrow">Case study</p><span className="case-study__number">{project.number}</span><p>{project.statusLabel}</p><p>{project.role}</p><nav aria-label="Case study sections"><a href="#overview">Overview</a><a href="#contribution">Contribution</a><a href="#evidence">Evidence</a><a href="#decisions">Decisions</a></nav></aside><div className="case-study__content"><header className="case-study__hero" id="overview"><p className="eyebrow">{project.number} / {project.eyebrow}</p><h1>{project.title}</h1><p className="case-study__summary">{project.summary}</p><div className="case-study__actions">{project.href && <a className="button button--primary" href={project.href} target="_blank" rel="noreferrer">View product <ArrowUpRight size={16} /></a>}{project.github && <a className="button" href={project.github} target="_blank" rel="noreferrer">View source <ArrowUpRight size={16} /></a>}</div></header><figure className="case-study__media"><img src={project.media.src} alt={project.media.alt} /><figcaption><span>{project.media.source}</span><span>{project.media.note}</span></figcaption></figure><section className="case-study__grid" id="contribution"><div><p className="eyebrow">The product</p><p>{project.whatItIs}</p></div><div><p className="eyebrow">Why it exists</p><p>{project.why}</p></div><div><p className="eyebrow">My contribution</p><p>{project.contribution}</p></div></section><section className="case-study__details" id="evidence"><article><p className="eyebrow">What I built</p><ul>{project.built.map((item) => <li key={item}>{item}</li>)}</ul></article><article><p className="eyebrow">How it works</p><ol>{project.architecture.map((item) => <li key={item}>{item}</li>)}</ol></article><article><p className="eyebrow">Evidence</p><ul>{project.evidence.map((item) => <li key={item}>{item}</li>)}</ul></article><article><p className="eyebrow">Skills</p><div className="tag-list">{project.skills.map((item) => <span key={item}>{item}</span>)}</div></article></section><section className="case-study__decisions" id="decisions"><div><p className="eyebrow">Decisions</p><ul>{project.decisions.map((item) => <li key={item}>{item}</li>)}</ul></div><div><p className="eyebrow">Lessons</p><ul>{project.lessons.map((item) => <li key={item}>{item}</li>)}</ul></div></section><section className="verified-block"><p className="eyebrow">Current status</p><p>{project.verified}</p></section><Link className="case-study__next" href={`/projects/${next.slug}`}><span><small>Next project</small>{next.title}</span><ArrowRight size={20} /></Link></div></div></main></>
}
